openapi: '3.0.2'
info:
  title: API Charity App
  version: '1.0'
servers:
  - url: http://127.0.0.1:8000
    description: Open On LocalHost
  - url: https://inaash-alfqeer.herokuapp.com/
    description: Optional server description, e.g. Internal server for testing

paths:
  /index:
    get:
      responses:
        '200':
          description: OK
